version: '3.9'

services:
  proxy:
    container_name: drinkarena-proxy
    build:
      context: .
      dockerfile: .docker/Dockerfile.proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/drinkarena.conf.template:/etc/nginx/templates/default.conf.template
    depends_on:
#      - database
      - php
    environment:
      PROXY_DOMAIN: drinkarena.eristich.dev
      PROXY_DOMAIN_ALIAS: localhost

  php:
    container_name: drinkarena-php
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.php
    ports:
      - "9000:9000"
#    volumes:
      #- ./:/var/www/drinkarena
#    depends_on:
#      - database
    environment:
#      DATABASE_URL: "postgresql://drinkarena:root@database:5432/drinkarena?serverVersion=15&charset=utf8"
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
