version: '3.9'

services:
  php:
    container_name: drinkarena-api-php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    networks:
      - drinkarena_net
  nginx:
    container_name: drinkarena-api-nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - drinkarena_net

networks:
  drinkarena_net:
